version: '3'

services:
  wavn:
    image: wavn:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Projects\Own\WAVN\trunk\WAVN:C:\inetpub\wwwroot
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\bin/WAVN.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
